# -*- coding: utf-8 -*-
"""ASSIGNMENT 2 (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1__qmx9-11TrDbeEzJMXJTGMuJqOlWSoW

#Write a Python program to get a list, sorted in increasing order by the last element in each tuple from a given list of non-empty tuples



#Sample List : [(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]

#Expected Result : [(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]
"""

# Take tuple input from the user
def take_tuple_input():
    tuples_list = []
    while True:
        user_input = input("Enter a tuple (comma-separated values) or 'q' to quit: ")
        if user_input.lower() == 'q':
            break
        values = tuple(map(int, user_input.split(',')))
        tuples_list.append(values)

    return tuples_list

# Call the function to take tuple input from the user
input_tuples = take_tuple_input()

# Sort the list of tuples based on the last element of each tuple
sorted_tuples = sorted(input_tuples, key=lambda x: x[-1])

# Print the sorted list of tuples
print("Sorted List of Tuples:", sorted_tuples)

