# -*- coding: utf-8 -*-
"""ASSIGNMENT 3 ..1..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KTLROmCoWxcpg-epFV5mawB0Fq5-UGsu
"""



def sum_list_numbers(numbers):
    sum = 0
    for num in numbers:
        sum += num
    return sum

# Get list input from the user
user_input = input("Enter a list of numbers separated by spaces: ")

# Convert the input string to a list of integers
try:
    user_list = [int(num) for num in user_input.split()]
except ValueError:
    print("Invalid input. Please enter numbers separated by spaces.")
    exit()

result = sum_list_numbers(user_list)
print("Sum of the numbers:", result)