# -*- coding: utf-8 -*-
"""ASSIGNMENT 3 ..3..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KTLROmCoWxcpg-epFV5mawB0Fq5-UGsu
"""



def count_upper_lower_case(input_string):
    upper_count = 0
    lower_count = 0

    for char in input_string:
        if char.isupper():
            upper_count += 1
        elif char.islower():
            lower_count += 1

    return upper_count, lower_count

# Get the input string from the user
user_input = input("Enter a string: ")

upper, lower = count_upper_lower_case(user_input)
print("No. of Upper case characters:", upper)
print("No. of Lower case characters:", lower)