# -*- coding: utf-8 -*-
"""ASSIGNMENT 3 ..2..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KTLROmCoWxcpg-epFV5mawB0Fq5-UGsu
"""

def reverse_string(input_string):
    return input_string[::-1]

# Get the input string from the user
sample_string = input("Enter a string: ")

reversed_string = reverse_string(sample_string)
print("Reversed String:", reversed_string)

