# -*- coding: utf-8 -*-
"""ASSIGNMENT2 (2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TW8rL977gQbdQVQbmfj6iJSI5k1rieZu

Write a Python program to print a dictionary whose keys should be the alphabet from a-z and the value should be corresponding ASCII values



Sample Output : {'a': 97, 'b': 98, 'c': 99, 'd': 100, 'e': 101, 'f': 102, 'g': 103, 'h': 104, 'i': 105, 'j': 106, 'k': 107, 'l': 108, 'm': 109, 'n': 110, 'o': 111, 'p': 112, 'q': 113, 'r': 114, 's': 115, 't': 116, 'u': 117, 'v': 118, 'w': 119, 'x': 120, 'y': 121, 'z': 122}
"""

def create_ascii_dict():
    ascii_dict = {chr(i): i for i in range(97, 123)}
    return ascii_dict

# Call the function to create the ASCII dictionary
ascii_dict = create_ascii_dict()

# Print the dictionary
print("Dictionary with ASCII values for alphabets from 'a' to 'z':")
print(ascii_dict)