# -*- coding: utf-8 -*-
"""Count even and odd numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K-nHW0UcZAhsu4jOaVJARS-JdQ_Dj-1M
"""

# Python program to count Even and Odd numbers in a List

numbers = (1,2,3,4,5,6,7,8,9)

even_count, odd_count = 0, 0
for num in numbers:
	if num % 2 == 0:
		even_count += 1
	else:
		odd_count  += 1

print("Number of even numbers : : ", even_count)
print("Number of odd numbers : : ", odd_count)

