# -*- coding: utf-8 -*-
"""Fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AxJTJcL5OT9dHwud8sWU1XmifOMzfqOQ
"""

#Write a Python program to get the Fibonacci series between 0 to 50

x = 0
y = 1

while y < 50:
  print(y,end=" ")
  x,y=y,x+y