# -*- coding: utf-8 -*-
"""Reversing string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tSCrWPU5qBTPJXZpcmJpNGwyfz4CA40y
"""



string=input("string:")
new_string =string[::-1]
print(new_string)

